#ifndef COMSTACK_CFG_H
#define COMSTACK_CFG_H

/*
Contents of file

[SWS_Comtype_00029] ⌈ComStack_Cfg.h shall be generated by the generator to
generate the type definition of the PduIdType and PduLengthType from the EcuC
Virtual Layer based on the configuration e.g. typedef uint8 PduIdType if number of
PDUs are less than 256. ⌋ ( )

[SWS_Comtype_00030] ⌈The value of PduIdType and PduLengthType shall be
derived from the ‘PduIdTypeEnum’ and ‘PduLengthTypeEnum’ of the
EcuCPduCollection container respectively. ⌋ ( )
*/

#endif /*COMSTACK_CFG_H*/
